version: 2

sources:
  - name: erp
    description: Fonte SAP de vendas Northwind
    schema: erp_northwind
    tables:
      - name: products
        columns:
          - name: product_id
            tests:
              - unique
              - not_null

      - name: categories
      - name: suppliers
      - name: employees
      - name: orders
        description: Uma linha para cada pedido (NF)
        columns:
          - name: order_id
            tests:
              - unique
              - not_null
      - name: order_details

